version: '2'
services:
  web:
    image: mario21ic/flaskredis
    #env_file:
    #  - build_number.env
    environment:
      - REDIS_HOST=172.21.0.2
      - REDIS_PORT=6379
    volumes:
     - ./src/:/code/
    ports:
     - 5000:5000

  redis:
    image: redis:alpine
    #ports:
    #  - 6379:6379

  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/web.conf:/etc/nginx/conf.d/web.conf
    ports:
      - 80:80
